### PR TITLE
fix broken cli

### PR DESCRIPTION
**Pull request by larrybahr**
Add shebang and cli entry

### CODE REVIEW

**Comment by larrybahr** [comment]
Created to fix issue https://github.com/franciscop/legally/pull/40#issuecomment-644843380

**Comment by larrybahr** [comment]
@franciscop If you give it the ok I will merge it.
@fabianbru confirmed it is working.

**Comment by franciscop** [comment]
This looks good, thanks! To publish it to npm I have a script that will auto-increment the version

**Comment by larrybahr** [comment]
Good to know. I will remember that for the future.

**Pull request merged**
