### PR TITLE
Use relative paths if root folder is relative

### PR DESCRIPTION
**Pull request by markwilson**
I found a problem when I had a project with "test" in the name (so the absolute `node_modules` path became `.../my-project-with-test-in-the-name/node_modules/`).

Using `files.walk` always gives the absolute paths to the files, so my entire dependencies folder was being ignored due to the project name.

I've updated the `legally` function to map the absolute path to a relative path when the root folder is also relative - if the root is absolute then it will continue to use the absolute path.

### CODE REVIEW

**Comment by markwilson** [comment]
The failed build seems to be also happening in `master` - I don't think this PR introduced it.

**Comment by franciscop** [comment]
Interesting issue, thanks for the PR! I think overall the walking itself is quite janky and could/should be rewritten at some point, but for now this seems like a good temp fix, thanks!

**Comment by franciscop** [comment]
Also I'm not using Appveyor anymore (now using Actions for tests) but couldn't figure out how to remove it from the project!

**Comment by franciscop** [comment]
I think I removed it successfully, the tests are passing on Windows as well, thanks!
https://github.com/franciscop/legally/actions/runs/240788189

**Comment by franciscop** [comment]
Published as `legally@3.5.7`

**Comment by markwilson** [comment]
Awesome! Thanks for doing it so quickly 💪

**Comment by markwilson** [comment]
Sorry, completely my fault... I didn't run the build to regenerate `index.min.js` as part of my PR - so `3.5.7` doesn't have the updated code 🤦‍♂️

**Comment by franciscop** [comment]
Ahh no that's on me, I run the "quick" [publish script that I have](https://github.com/franciscop/happy/) because I forgot this project had a `build` step, published as `legally@3.5.8` :tada:

**Pull request merged**
